export const navigationTopItems = [
  { id: 'overview', name: 'Overview' },
];

export const navigationSections = [
  {
    id: 'system',
    title: 'System',
    items: [
      { id: 'a11y-checks', name: 'Accessibility Checks' },
      { id: 'component-communication', name: 'Component Communication' },
      { id: 'components-provider', name: 'Component Provider' },
      { id: 'product-catalog', name: 'Product Catalog' },
      { id: 'system-utilities', name: 'Utilities' },
    ]
  },
  {
    id: 'media',
    title: 'Media',
    items: [
      { id: 'media', name: 'Brand Media' },
      { id: 'icons', name: 'Icons' },
      { id: 'illustrations', name: 'Illustrations' },
      { id: 'lottie', name: 'Lottie' },
    ]
  },
  {
    id: 'patterns',
    title: 'Patterns',
    items: [
      { id: 'patterns-case-study-template', name: 'Case Study Template' },
      { id: 'patterns-case-study-components', name: 'Case Study Components' },
      { id: 'patterns-case-study-typography', name: 'Case Study Typography' },
      { id: 'patterns-case-study-primitives', name: 'Case Study Primitives' },
      { id: 'patterns-agent-canvas', name: 'Agent Canvas' },
      { id: 'patterns-processing-trace', name: 'Processing Trace' },
      { id: 'components-accordion', name: 'Accordion' },
      { id: 'patterns-associate', name: 'Associate Patterns' },
      { id: 'patterns-carousels-grids', name: 'Carousels & Grids' },
      { id: 'patterns-clocking-widget', name: 'Clocking Widget' },
      { id: 'patterns-data-viz', name: 'Data Viz' },
      { id: 'patterns-footer', name: 'Footer' },
      { id: 'patterns-header', name: 'Header' },
      { id: 'components-intelligent-insight', name: 'Intelligent Insight' },
      { id: 'components-intelligent-recommendation', name: 'Intelligent Recommendation' },
      { id: 'components-item-recommendation', name: 'Item Recommendation' },
      { id: 'components-item-tile', name: 'Item Tile' },
      { id: 'components-item-tile-condensed', name: 'Item Tile Condensed' },
      { id: 'patterns-list-action', name: 'List · Action' },
      { id: 'patterns-list-associate', name: 'List · Associate' },
      { id: 'patterns-list-goal', name: 'List · Goal' },
      { id: 'patterns-list-members', name: 'List · Members' },
      { id: 'patterns-mobile-mega-nav', name: 'Mobile MegaNav' },
      { id: 'patterns-native-navigation', name: 'Native Navigation' },
      { id: 'patterns-order-card', name: 'Order Card' },
      { id: 'patterns-order-status', name: 'Order Status' },
      { id: 'patterns-queue', name: 'Queue' },
      { id: 'patterns-schedule-widget', name: 'Schedule Widget' },
      { id: 'patterns-search-results', name: 'Search Results' },
      { id: 'components-sidebar', name: 'Sidebar' },
      { id: 'patterns-side-navigation', name: 'Side Navigation' },
      { id: 'patterns-side-navigation-ax', name: 'Side Navigation (AX)' },
      { id: 'patterns-table-pagination', name: 'Table Pagination' },
      { id: 'patterns-agent-sidebar', name: 'Agent Sidebar' },
      { id: 'patterns-app-header', name: 'App Header' },
      { id: 'patterns-ax-bottom-nav', name: 'Associate Bottom Nav' },
      { id: 'patterns-auto-care-upsell-offer-card', name: 'Auto Care Upsell Offer Card' },
      { id: 'patterns-carousel-product-card', name: 'Carousel Product Card' },
      { id: 'patterns-delayed-delivery-card', name: 'Delayed Delivery Card' },
      { id: 'patterns-flash-deals-item-tile', name: 'Flash Deals Item Tile' },
      { id: 'patterns-maintenance-health-card', name: 'Maintenance Health Card' },
      { id: 'patterns-product-card-grid', name: 'Product Card (Grid)' },
      { id: 'patterns-product-card-list', name: 'Product Card (List)' },
      { id: 'patterns-promotional-item-tile', name: 'Promotional Item Tile' },
    ]
  },
  {
    id: 'components',
    title: 'Components',
    items: [
      { id: 'components-action-tile', name: 'Tiles' },
      { id: 'components-action-group', name: 'Action Group' },
      { id: 'components-action-group-walmart', name: 'Action Group (Walmart)' },
      { id: 'components-alert', name: 'Alert' },
      { id: 'components-alert-dialog', name: 'Alert Dialog' },
      { id: 'components-aspect-ratio', name: 'Aspect Ratio' },
      { id: 'components-attribute', name: 'Attribute' },
      { id: 'components-avatar', name: 'Avatar' },
      { id: 'components-badge', name: 'Badge' },
      { id: 'components-banner', name: 'Banner' },
      { id: 'components-basic-banner', name: 'Basic Banner' },
      { id: 'components-bottom-sheet', name: 'Bottom Sheet' },
      { id: 'components-breadcrumb', name: 'Breadcrumb' },
      { id: 'components-button', name: 'Button' },
      { id: 'components-button-toggle', name: 'Button Toggle' },
      { id: 'components-callout', name: 'Callout' },
      { id: 'components-card', name: 'Card' },
      { id: 'components-carousel', name: 'Carousel' },
      { id: 'components-category-nav', name: 'Category Nav' },
      { id: 'components-checkbox', name: 'Checkbox' },
      { id: 'components-chip', name: 'Chip' },
      { id: 'components-command', name: 'Command' },
      { id: 'components-content-card', name: 'Content Card' },
      { id: 'components-content-message', name: 'Content Message' },
      { id: 'components-context-menu', name: 'Context Menu' },
      { id: 'components-country-select', name: 'Country Select' },
      { id: 'components-data-table', name: 'Data Table' },
      { id: 'components-data-table-config-panel', name: 'Data Table Config Panel' },
      { id: 'components-date-picker', name: 'Date Picker' },
      { id: 'components-date-picker-calendar', name: 'Date Picker Calendar' },
      { id: 'components-date-range-picker', name: 'Date Range Picker' },
      { id: 'components-divider', name: 'Divider' },
      { id: 'components-flag', name: 'Flag' },
      { id: 'components-floating-button', name: 'Floating Button' },
      { id: 'components-form', name: 'Form' },
      { id: 'components-form-group', name: 'Form Group' },
      { id: 'components-header-instructional', name: 'Header Instructional' },
      { id: 'components-header-section', name: 'Header Section' },
      { id: 'components-header-widget', name: 'Header Widget' },
      { id: 'components-heart-view', name: 'Heart View' },
      { id: 'components-highlight-text', name: 'Highlight Text' },
      { id: 'components-icon-button', name: 'Icon Button' },
      { id: 'components-icon-selector', name: 'Icon Selector' },
      { id: 'components-language-selector', name: 'Language Selector' },
      { id: 'components-link', name: 'Link' },
      { id: 'components-link-button', name: 'Link Button' },
      { id: 'components-list', name: 'List' },
      { id: 'components-location-breadcrumb', name: 'Location Breadcrumb' },
      { id: 'components-magic-box', name: 'Magic Box' },
      { id: 'components-masthead', name: 'Masthead' },
      { id: 'components-menu', name: 'Menu' },
      { id: 'components-menubar', name: 'Menubar' },
      { id: 'components-metric', name: 'Metric' },
      { id: 'components-metric-group', name: 'Metric Group' },
      { id: 'components-modal', name: 'Modal' },
      { id: 'components-nudge', name: 'Nudge' },
      { id: 'components-pagination', name: 'Pagination' },
      { id: 'components-panel', name: 'Panel' },
      { id: 'components-placeholder-media', name: 'Placeholder Media' },
      { id: 'components-popover', name: 'Popover' },
      { id: 'components-progress-indicator', name: 'Progress Indicator' },
      { id: 'components-progress-tracker', name: 'Progress Tracker' },
      { id: 'components-quantity-stepper', name: 'Quantity Stepper' },
      { id: 'components-radio', name: 'Radio' },
      { id: 'components-rating', name: 'Rating' },
      { id: 'components-rating-display', name: 'Rating Display' },
      { id: 'components-resizable', name: 'Resizable' },
      { id: 'components-rich-media-sheet', name: 'Rich Media Sheet' },
      { id: 'components-rich-snackbar', name: 'Rich Snackbar' },
      { id: 'components-rich-text-editor', name: 'Rich Text Editor' },
      { id: 'components-scroll-area', name: 'Scroll Area' },
      { id: 'components-scrim-overlay', name: 'Scrim Overlay' },
      { id: 'components-search-bar', name: 'Search Bar' },
      { id: 'components-section-header', name: 'Section Header' },
      { id: 'components-segmented-control', name: 'Segmented Control' },
      { id: 'components-select', name: 'Select' },
      { id: 'components-select-card', name: 'Select Card' },
      { id: 'components-select-dropdown', name: 'Select Dropdown' },
      { id: 'components-signature-capture', name: 'Signature Capture' },
      { id: 'components-skeleton', name: 'Skeleton' },
      { id: 'components-slider', name: 'Slider' },
      { id: 'components-slot', name: 'Slot' },
      { id: 'components-snackbar', name: 'Snackbar' },
      { id: 'components-spin-button', name: 'SpinButton' },
      { id: 'components-spinner', name: 'Spinner' },
      { id: 'components-spot-icon', name: 'Spot Icon' },
      { id: 'components-switch', name: 'Switch' },
      { id: 'components-tab-navigation', name: 'Tab Navigation' },
      { id: 'components-tag', name: 'Tag' },
      { id: 'components-tag-interactive', name: 'Tag Interactive' },
      { id: 'components-text-area', name: 'Text Area' },
      { id: 'components-text-field', name: 'Text Field' },
      { id: 'components-timer-view', name: 'Timer View' },
      { id: 'components-toggle', name: 'Toggle' },
      { id: 'components-toggle-group', name: 'Toggle Group' },
      { id: 'components-tooltip', name: 'Tooltip' },
      { id: 'components-tree', name: 'Tree' },
      { id: 'components-upload-file', name: 'Upload File' },
      { id: 'components-upload-image', name: 'Upload Image' },
      { id: 'components-agent-response', name: 'Agent Response' },
      { id: 'components-attachment-tile', name: 'Attachment Tile' },
      { id: 'components-bottom-nav', name: 'Bottom Nav' },
      { id: 'components-circular-progress', name: 'Circular Progress' },
      { id: 'components-clock-status', name: 'Clock Status' },
      { id: 'components-collapse', name: 'Collapse' },
      { id: 'components-collapsible', name: 'Collapsible' },
      { id: 'components-combobox', name: 'Combobox' },
      { id: 'components-container', name: 'Container' },
      { id: 'components-country-code-phone-input', name: 'Country Code Phone Input' },
      { id: 'components-date-field', name: 'Date Field' },
      { id: 'components-error-message', name: 'Error Message' },
      { id: 'components-feedback', name: 'Feedback' },
      { id: 'components-filter-chip', name: 'Filter Chip' },
      { id: 'components-fluent-menu', name: 'Fluent Menu' },
      { id: 'components-gauge', name: 'Gauge' },
      { id: 'components-grid', name: 'Grid' },
      { id: 'components-image', name: 'Image' },
      { id: 'components-label', name: 'Label' },
      { id: 'components-line-clamp', name: 'Line Clamp' },
      { id: 'components-logo', name: 'Logo' },
      { id: 'components-page', name: 'Page' },
      { id: 'components-page-header', name: 'Page Header' },
      { id: 'components-prompt-composer', name: 'Prompt Composer' },
      { id: 'components-search-field', name: 'Search Field' },
      { id: 'components-section', name: 'Section' },
      { id: 'components-skyline-banner', name: 'Skyline Banner' },
      { id: 'components-sources', name: 'Sources' },
      { id: 'components-text', name: 'Text' },
      { id: 'components-text-field-split', name: 'Text Field Split' },
      { id: 'components-user-response', name: 'User Response' },
    ]
  }
// Items are sorted alphabetically by display name at runtime, so the source
// order above does not affect what renders — add new entries anywhere.
// Explicit 'en' locale + base sensitivity keeps ordering deterministic across
// Node/browser environments and special characters (e.g. the "·" in list items).
].map(section => ({
  ...section,
  items: [...section.items].sort((a, b) =>
    a.name.localeCompare(b.name, 'en', {sensitivity: 'base'}),
  ),
}));
