/* Auto-generated from Airtable "All Media" view — do not edit by hand */

import { WCP_MEDIA_SVGS, WCP_MEDIA_IMAGES, WCP_MEDIA_TOKENS } from './wcp';
import { WALMART_BUSINESS_MEDIA_SVGS, WALMART_BUSINESS_MEDIA_IMAGES, WALMART_BUSINESS_MEDIA_TOKENS } from './walmart-business';
import { WALMART_LEGACY_MEDIA_SVGS, WALMART_LEGACY_MEDIA_IMAGES, WALMART_LEGACY_MEDIA_TOKENS } from './walmart-legacy';
import { WALMART_MX_MEDIA_SVGS, WALMART_MX_MEDIA_IMAGES, WALMART_MX_MEDIA_TOKENS } from './walmart-mx';
import { WALMART_CA_MEDIA_SVGS, WALMART_CA_MEDIA_IMAGES, WALMART_CA_MEDIA_TOKENS } from './walmart-ca';
import { WALMART_PLUS_MEDIA_SVGS, WALMART_PLUS_MEDIA_IMAGES, WALMART_PLUS_MEDIA_TOKENS } from './walmart-plus';
import { SAMS_CLUB_MEDIA_SVGS, SAMS_CLUB_MEDIA_IMAGES, SAMS_CLUB_MEDIA_TOKENS } from './sams-club';
import { SAMS_CLUB_MAVERICK_MEDIA_SVGS, SAMS_CLUB_MAVERICK_MEDIA_IMAGES, SAMS_CLUB_MAVERICK_MEDIA_TOKENS } from './sams-club-maverick';
import { MEMBERS_MARK_MEDIA_SVGS, MEMBERS_MARK_MEDIA_IMAGES, MEMBERS_MARK_MEDIA_TOKENS } from './members-mark';
import { BODEGA_MEDIA_SVGS, BODEGA_MEDIA_IMAGES, BODEGA_MEDIA_TOKENS } from './bodega';

/** Media theme key → PascalCase name → inline SVG string. */
export const MEDIA_SVGS: Record<string, Record<string, string>> = {
  'wcp': WCP_MEDIA_SVGS,
  'walmart-business': WALMART_BUSINESS_MEDIA_SVGS,
  'walmart-legacy': WALMART_LEGACY_MEDIA_SVGS,
  'walmart-mx': WALMART_MX_MEDIA_SVGS,
  'walmart-ca': WALMART_CA_MEDIA_SVGS,
  'walmart-plus': WALMART_PLUS_MEDIA_SVGS,
  'sams-club': SAMS_CLUB_MEDIA_SVGS,
  'sams-club-maverick': SAMS_CLUB_MAVERICK_MEDIA_SVGS,
  'members-mark': MEMBERS_MARK_MEDIA_SVGS,
  'bodega': BODEGA_MEDIA_SVGS,
};

/** Media theme key → PascalCase name → `data:image/png;base64,...` URL. */
export const MEDIA_IMAGES: Record<string, Record<string, string>> = {
  'wcp': WCP_MEDIA_IMAGES,
  'walmart-business': WALMART_BUSINESS_MEDIA_IMAGES,
  'walmart-legacy': WALMART_LEGACY_MEDIA_IMAGES,
  'walmart-mx': WALMART_MX_MEDIA_IMAGES,
  'walmart-ca': WALMART_CA_MEDIA_IMAGES,
  'walmart-plus': WALMART_PLUS_MEDIA_IMAGES,
  'sams-club': SAMS_CLUB_MEDIA_IMAGES,
  'sams-club-maverick': SAMS_CLUB_MAVERICK_MEDIA_IMAGES,
  'members-mark': MEMBERS_MARK_MEDIA_IMAGES,
  'bodega': BODEGA_MEDIA_IMAGES,
};

/** Media theme key → PascalCase name → Airtable token name. */
export const MEDIA_TOKENS: Record<string, Record<string, string>> = {
  'wcp': WCP_MEDIA_TOKENS,
  'walmart-business': WALMART_BUSINESS_MEDIA_TOKENS,
  'walmart-legacy': WALMART_LEGACY_MEDIA_TOKENS,
  'walmart-mx': WALMART_MX_MEDIA_TOKENS,
  'walmart-ca': WALMART_CA_MEDIA_TOKENS,
  'walmart-plus': WALMART_PLUS_MEDIA_TOKENS,
  'sams-club': SAMS_CLUB_MEDIA_TOKENS,
  'sams-club-maverick': SAMS_CLUB_MAVERICK_MEDIA_TOKENS,
  'members-mark': MEMBERS_MARK_MEDIA_TOKENS,
  'bodega': BODEGA_MEDIA_TOKENS,
};

export { WCP_MEDIA_SVGS, WCP_MEDIA_IMAGES, WCP_MEDIA_TOKENS };
export { WALMART_BUSINESS_MEDIA_SVGS, WALMART_BUSINESS_MEDIA_IMAGES, WALMART_BUSINESS_MEDIA_TOKENS };
export { WALMART_LEGACY_MEDIA_SVGS, WALMART_LEGACY_MEDIA_IMAGES, WALMART_LEGACY_MEDIA_TOKENS };
export { WALMART_MX_MEDIA_SVGS, WALMART_MX_MEDIA_IMAGES, WALMART_MX_MEDIA_TOKENS };
export { WALMART_CA_MEDIA_SVGS, WALMART_CA_MEDIA_IMAGES, WALMART_CA_MEDIA_TOKENS };
export { WALMART_PLUS_MEDIA_SVGS, WALMART_PLUS_MEDIA_IMAGES, WALMART_PLUS_MEDIA_TOKENS };
export { SAMS_CLUB_MEDIA_SVGS, SAMS_CLUB_MEDIA_IMAGES, SAMS_CLUB_MEDIA_TOKENS };
export { SAMS_CLUB_MAVERICK_MEDIA_SVGS, SAMS_CLUB_MAVERICK_MEDIA_IMAGES, SAMS_CLUB_MAVERICK_MEDIA_TOKENS };
export { MEMBERS_MARK_MEDIA_SVGS, MEMBERS_MARK_MEDIA_IMAGES, MEMBERS_MARK_MEDIA_TOKENS };
export { BODEGA_MEDIA_SVGS, BODEGA_MEDIA_IMAGES, BODEGA_MEDIA_TOKENS };
