/**
 * `ld-kit list` and `ld-kit show <Name>` implementations.
 *
 * Both read the bundled component manifest at
 * <package-root>/living-design/components.json, generated by
 * scripts/extract-guidelines.mjs.
 */
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";

const RED = "\x1b[31m";
const BOLD = "\x1b[1m";
const DIM = "\x1b[2m";
const RESET = "\x1b[0m";

const SKILL_ROOT_URL = new URL("../living-design/", import.meta.url);
const MANIFEST_PATH = fileURLToPath(new URL("components.json", SKILL_ROOT_URL));

interface PropEntry {
  name: string;
  type: string;
  required: boolean;
  description?: string;
}

interface ComponentEntry {
  name: string;
  category: "components" | "patterns" | "other";
  importPath: string;
  intent?: string;
  hasNarrativeDoc: boolean;
  docPath: string;
  props: PropEntry[];
}

interface Manifest {
  version: number;
  generated: string;
  counts: { total: number; components: number; patterns: number };
  components: ComponentEntry[];
}

const CATEGORIES = ["components", "patterns", "other"] as const;
type Category = (typeof CATEGORIES)[number];

const CATEGORY_TITLES: Record<Category, string> = {
  components: "Components (atoms + molecules)",
  patterns: "Patterns (composed organisms)",
  other: "Other",
};

const CATEGORY_HELP = "components | patterns";

function loadManifest(): Manifest {
  if (!existsSync(MANIFEST_PATH)) {
    process.stderr.write(
      `${RED}Error: component manifest not found at ${MANIFEST_PATH}.\nThis @walmart/ld-kit installation appears to be corrupted — try reinstalling the package.${RESET}\n`
    );
    process.exit(1);
  }
  return JSON.parse(readFileSync(MANIFEST_PATH, "utf-8")) as Manifest;
}

export interface ListOptions {
  category?: string;
  grep?: string;
}

export function list(opts: ListOptions = {}): void {
  const manifest = loadManifest();
  let components = manifest.components;

  if (opts.category) {
    const cat = opts.category.toLowerCase();
    components = components.filter((c) => c.category === cat);
    if (components.length === 0) {
      process.stderr.write(
        `${RED}No components in category "${opts.category}". Valid categories: ${CATEGORY_HELP}.${RESET}\n`
      );
      process.exit(1);
    }
  }

  if (opts.grep) {
    const needle = opts.grep.toLowerCase();
    components = components.filter(
      (c) =>
        c.name.toLowerCase().includes(needle) ||
        (c.intent ?? "").toLowerCase().includes(needle)
    );
    if (components.length === 0) {
      process.stderr.write(`${RED}No components match "${opts.grep}".${RESET}\n`);
      process.exit(1);
    }
  }

  const groups: Record<Category, ComponentEntry[]> = {
    components: [],
    patterns: [],
    other: [],
  };
  for (const c of components) {
    // Tolerate manifest entries with an unknown category (e.g. a future
    // additional bucket) by falling back to "other" instead of crashing.
    const bucket = (CATEGORIES as readonly string[]).includes(c.category)
      ? (c.category as Category)
      : "other";
    groups[bucket].push(c);
  }

  for (const cat of CATEGORIES) {
    if (groups[cat].length === 0) continue;
    console.log(`\n${BOLD}${CATEGORY_TITLES[cat]} (${groups[cat].length})${RESET}`);
    const nameWidth = Math.max(
      ...groups[cat].map((c) => c.name.length),
      4
    );
    const importWidth = Math.max(
      ...groups[cat].map((c) => c.importPath.length),
      6
    );
    for (const c of groups[cat]) {
      const intent = c.intent ? `  ${DIM}${c.intent}${RESET}` : "";
      console.log(
        `  ${c.name.padEnd(nameWidth)}  ${c.importPath.padEnd(importWidth)}${intent}`
      );
    }
  }
  console.log(
    `\n${DIM}Run \`ld-kit show <Name>\` for prop API + usage notes.${RESET}`
  );
}

export function show(name: string): void {
  const manifest = loadManifest();
  const exact = manifest.components.find((c) => c.name === name);
  const target =
    exact ??
    manifest.components.find(
      (c) => c.name.toLowerCase() === name.toLowerCase()
    );

  if (!target) {
    const suggestions = manifest.components
      .filter((c) => c.name.toLowerCase().includes(name.toLowerCase()))
      .slice(0, 5)
      .map((c) => c.name);
    process.stderr.write(`${RED}No component named "${name}".${RESET}\n`);
    if (suggestions.length > 0) {
      process.stderr.write(`Did you mean: ${suggestions.join(", ")}?\n`);
    } else {
      process.stderr.write(`Run \`ld-kit list\` to see every component.\n`);
    }
    process.exit(1);
  }

  // Prefer the rendered per-component markdown that sits next to the
  // component's .tsx — it includes the hand-authored narrative on top of the
  // prop API. Fall back to re-rendering from JSON if the file is missing.
  const docFile = fileURLToPath(new URL(target.docPath, SKILL_ROOT_URL));
  if (existsSync(docFile)) {
    process.stdout.write(readFileSync(docFile, "utf-8"));
    return;
  }

  // Fallback rendering — keeps `show` working even when the docs dir was not
  // packaged for some reason.
  const lines: string[] = [
    `# ${target.name}`,
    "",
    `Import:   import { ${target.name} } from "${target.importPath}"`,
    `Category: ${target.category}`,
  ];
  if (target.intent) lines.push(`Intent:   ${target.intent}`);
  lines.push("", "Props:");
  if (target.props.length === 0) {
    lines.push("  (no public props)");
  } else {
    for (const p of target.props) {
      const req = p.required ? " (required)" : "";
      const desc = p.description ? ` — ${p.description.split("\n")[0]}` : "";
      lines.push(`  ${p.name}: ${p.type}${req}${desc}`);
    }
  }
  console.log(lines.join("\n"));
}
