export const THEME_OPTIONS = [
  {
    name: "Portfolio",
    label: "Portfolio",
    description:
      "Amy's portfolio brand — purple CTAs (#4F39F6), indigo accents, and violet surfaces matching the site shell.",
    swatch: "#4F39F6",
  },
  {
    name: "WM",
    label: "WM",
    description:
      "Waste Management rebrand — WM.com greens (#006937) used in the WM case study.",
    swatch: "#006937",
  },
  {
    name: "Oportun",
    label: "Oportun",
    description:
      "Digit/Oportun rebrand — TT Commons Classic typography and brand greens (#6CDB8C).",
    swatch: "#6CDB8C",
  },
  {
    name: "Walmart",
    label: "Walmart",
    description: "Default Living Design / Walmart blue.",
    swatch: "#0053e2",
  },
  {
    name: "Sam's Club",
    label: "Sam's Club",
    description: "Warehouse club theme with Gibson typography.",
    swatch: "#0062ad",
  },
  {
    name: "Sam's Club Maverick",
    label: "Sam's Club Maverick",
    description: "Sam's Club refresh with brighter blue.",
    swatch: "#0a6cff",
  },
  {
    name: "Walmart B2B",
    label: "Walmart B2B",
    description: "Business theme with a deeper blue identity.",
    swatch: "#002e99",
  },
  {
    name: "Bodega",
    label: "Bodega",
    description: "Mexico retail theme with green brand tokens.",
    swatch: "#2a8703",
  },
  {
    name: "Cashi MX",
    label: "Cashi MX",
    description: "Mexico financial services with purple accents.",
    swatch: "#6212b2",
  },
  {
    name: "Walmart Legacy",
    label: "Walmart Legacy",
    description: "Classic Walmart brand system.",
    swatch: "#0071dc",
  },
] as const;

export type ComponentLibraryThemeName = (typeof THEME_OPTIONS)[number]["name"];

export const COMPONENT_NAMES = [
  "A11yAnnouncement",
  "A11yDevAssertions",
  "ActionGroup",
  "ActionTile",
  "AgentCanvas",
  "AgentResponse",
  "Alert",
  "AlertDialog",
  "AspectRatio",
  "AttachmentTile",
  "Attribute",
  "Avatar",
  "Badge",
  "Banner",
  "BasicBanner",
  "BottomNav",
  "BottomSheet",
  "Breadcrumb",
  "Button",
  "ButtonGroupPatterns",
  "ButtonToggle",
  "Callout",
  "Card",
  "Carousel",
  "CategoryNav",
  "Checkbox",
  "Chip",
  "CircularProgress",
  "ClockStatus",
  "Collapse",
  "Collapsible",
  "Combobox",
  "Command",
  "Container",
  "ContentCard",
  "ContentMessage",
  "ContextMenu",
  "CountryCodePhoneInput",
  "CountrySelectBottomSheet",
  "CountrySelectDropdown",
  "CountrySelectGroup",
  "DataTable",
  "DataTableConfigPanel",
  "DataTableTitle",
  "DataViz",
  "DateField",
  "DatePicker",
  "DatePickerCalendar",
  "DateRangePicker",
  "DefaultBreakpoint",
  "Divider",
  "ErrorMessage",
  "Feedback",
  "FilterChip",
  "Flag",
  "FloatingButton",
  "FluentMenu",
  "FocusTrap",
  "Form",
  "FormGroup",
  "Gauge",
  "Grid",
  "HeaderInstructional",
  "HeaderSection",
  "HeaderWidget",
  "HeartView",
  "HighlightText",
  "IconButton",
  "Icons",
  "IconSelector",
  "Image",
  "Label",
  "LanguageSelector",
  "LayoutContainer",
  "LineClamp",
  "Link",
  "LinkButton",
  "List",
  "LivingDesign",
  "LocationBreadcrumb",
  "Logo",
  "MagicBox",
  "Masthead",
  "Menu",
  "Menubar",
  "Metric",
  "MetricGroup",
  "Modal",
  "Nudge",
  "Overlay",
  "Page",
  "PageHeader",
  "Pagination",
  "Panel",
  "Popover",
  "ProcessingTrace",
  "ProgressIndicator",
  "ProgressTracker",
  "PromptComposer",
  "QuantityStepper",
  "Radio",
  "Rating",
  "RatingDisplay",
  "RatingStars",
  "Resizable",
  "RichMediaSheet",
  "RichSnackbar",
  "RichTextEditor",
  "Scrim",
  "ScrimOverlay",
  "ScrollArea",
  "SearchBar",
  "SearchField",
  "Section",
  "SectionHeader",
  "SegmentedControl",
  "Select",
  "SelectCard",
  "SelectDropdown",
  "SideNavigation",
  "SignatureCapture",
  "SignatureCaptureBottomSheet",
  "SignatureCapturePanel",
  "Skeleton",
  "SkylineBanner",
  "Slider",
  "Slot",
  "Snackbar",
  "Sources",
  "SpinButton",
  "Spinner",
  "SpotIcon",
  "SsrBoundary",
  "Switch",
  "TabNavigation",
  "Tag",
  "TagInteractive",
  "Text",
  "TextArea",
  "TextField",
  "TextFieldSplit",
  "TimerView",
  "Toggle",
  "ToggleGroup",
  "Tooltip",
  "UploadFile",
  "UploadImage",
  "UserResponse",
  "VisuallyHidden",
] as const;
